package org.test.boris.testapp.data.api.domain.entity;

// Generated 24.07.2015 14:27:28 by Hibernate Tools 4.3.1

import java.util.Date;


/**
 * CurrCourse generated by hbm2java
 */

public class CurrCourse implements java.io.Serializable {

	private static final long serialVersionUID = 5228338314792662L;

	private int id;
	private Integer version;
	private Integer popularity;
	private String createdby;
	private Date createon;
	private Integer firmid;
	private String lastmodifiedby;
	private Date modifyon;
	private String serieskey;
	private String label;
	private Integer course;
	private Integer currency;
	private Date datecourse;

	public CurrCourse() {
	}


	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	public String getCreatedby() {
		return this.createdby;
	}

	public void setCreatedby(String createdby) {
		this.createdby = createdby;
	}

	public Date getCreateon() {
		return this.createon;
	}

	public void setCreateon(Date createon) {
		this.createon = createon;
	}

	public Integer getFirmid() {
		return this.firmid;
	}

	public void setFirmid(Integer firmid) {
		this.firmid = firmid;
	}

	public String getLastmodifiedby() {
		return this.lastmodifiedby;
	}

	public void setLastmodifiedby(String lastmodifiedby) {
		this.lastmodifiedby = lastmodifiedby;
	}

	public Date getModifyon() {
		return this.modifyon;
	}

	public void setModifyon(Date modifyon) {
		this.modifyon = modifyon;
	}

	public String getSerieskey() {
		return this.serieskey;
	}

	public void setSerieskey(String serieskey) {
		this.serieskey = serieskey;
	}

	public Integer getCourse() {
		return this.course;
	}

	public void setCourse(Integer course) {
		this.course = course;
	}

	public Integer getCurrency() {
		return currency;
	}

	public void setCurrency(Integer currency) {
		this.currency = currency;
	}

	public String getLabel() {
		return label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	public Integer getPopularity() {
		return popularity;
	}

	public void setPopularity(Integer popularity) {
		this.popularity = popularity;
	}

	public Date getDatecourse() {
		return this.datecourse;
	}

	public void setDatecourse(Date datecourse) {
		this.datecourse = datecourse;
	}

}
